# Generated by Django 4.2.3 on 2023-09-19 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_mailtext_mailing_alter_mailing_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtext',
            name='mailing',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.mailtext', verbose_name='Сообщение'),
        ),
    ]
