# Generated by Django 4.2.3 on 2023-09-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_remove_mailtext_mailing_alter_mailing_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglog',
            name='mailing',
        ),
    ]
