# Generated by Django 4.2.3 on 2023-09-21 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0014_alter_mailtext_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mailing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newsletter.mailing', verbose_name='Рассылка'),
            preserve_default=False,
        ),
    ]
