# Generated by Django 4.2.3 on 2023-09-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0018_mailingcustomer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailingCustomer',
        ),
    ]
